require "mongoid"
require "nokogiri"
require "open-uri"
require "twitter"
require "stringex"

require "newest_latest/feed"
require "newest_latest/maker"
require "newest_latest/mongoid"
require "newest_latest/project"
require "newest_latest/version"
